version: "3.8"
services:

  #Database server
  database:
    image: mysql:8.0
    ports: 
        - "3307:3306"
    environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      

volumes:
  db-data: ~
